Vagrant.configure("2") do |config|
  
  # Box configuration
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "web"
  
  # Network configuration
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Provider configuration
  config.vm.provider "virtualbox" do |vb|
    vb.name = "web"
    vb.memory = "1024"
    vb.cpus = 1
  end

  # Configure the provisioning script
  config.vm.provision "shell", path: "bootstrap.sh"

end
