Vagrant.configure("2") do |config|
  # Usa una imagen ligera de Ubuntu 22.04
  config.vm.box = "ubuntu/jammy64"
  
  # Configuración de red (accesible via IP)
  config.vm.network "private_network", ip: "192.168.56.10"
  
  # Provisionamiento con Shell
  config.vm.provision "shell", path: "scripts/docker_install.sh", run: "once"
  config.vm.provision "shell", path: "scripts/kubectl_install.sh", run: "once"
  config.vm.provision "shell", path: "scripts/version_verify.sh", run: "once"

end


